// Simple periodic table data up to 118
// Each element has atomic number, symbol, row, and column (group)
export const elements = [
  {},
  // Period 1
  { num: 1, sym: "H", row: 1, col: 1, group: "group1" },
  { num: 2, sym: "He", row: 1, col: 18, group: "group18" },
  // Period 2
  { num: 3, sym: "Li", row: 2, col: 1, group: "group1" },
  { num: 4, sym: "Be", row: 2, col: 2, group: "group2" },
  { num: 5, sym: "B", row: 2, col: 13, group: "metalloid" },
  { num: 6, sym: "C", row: 2, col: 14, group: "mainGroup" },
  { num: 7, sym: "N", row: 2, col: 15, group: "mainGroup" },
  { num: 8, sym: "O", row: 2, col: 16, group: "mainGroup" },
  { num: 9, sym: "F", row: 2, col: 17, group: "group17" },
  { num: 10, sym: "Ne", row: 2, col: 18, group: "group18" },
  // Period 3
  { num: 11, sym: "Na", row: 3, col: 1, group: "group1" },
  { num: 12, sym: "Mg", row: 3, col: 2, group: "group2" },
  { num: 13, sym: "Al", row: 3, col: 13, group: "postTransition" },
  { num: 14, sym: "Si", row: 3, col: 14, group: "metalloid" },
  { num: 15, sym: "P", row: 3, col: 15, group: "mainGroup" },
  { num: 16, sym: "S", row: 3, col: 16, group: "mainGroup" },
  { num: 17, sym: "Cl", row: 3, col: 17, group: "group17" },
  { num: 18, sym: "Ar", row: 3, col: 18, group: "group18" },
  // Period 4
  { num: 19, sym: "K", row: 4, col: 1, group: "group1" },
  { num: 20, sym: "Ca", row: 4, col: 2, group: "group2" },
  { num: 21, sym: "Sc", row: 4, col: 3, group: "transition" },
  { num: 22, sym: "Ti", row: 4, col: 4, group: "transition" },
  { num: 23, sym: "V", row: 4, col: 5, group: "transition" },
  { num: 24, sym: "Cr", row: 4, col: 6, group: "transition" },
  { num: 25, sym: "Mn", row: 4, col: 7, group: "transition" },
  { num: 26, sym: "Fe", row: 4, col: 8, group: "transition" },
  { num: 27, sym: "Co", row: 4, col: 9, group: "transition" },
  { num: 28, sym: "Ni", row: 4, col: 10, group: "transition" },
  { num: 29, sym: "Cu", row: 4, col: 11, group: "transition" },
  { num: 30, sym: "Zn", row: 4, col: 12, group: "transition" },
  { num: 31, sym: "Ga", row: 4, col: 13, group: "postTransition" },
  { num: 32, sym: "Ge", row: 4, col: 14, group: "metalloid" },
  { num: 33, sym: "As", row: 4, col: 15, group: "metalloid" },
  { num: 34, sym: "Se", row: 4, col: 16, group: "mainGroup" },
  { num: 35, sym: "Br", row: 4, col: 17, group: "group17" },
  { num: 36, sym: "Kr", row: 4, col: 18, group: "group18" },
  // Period 5
  { num: 37, sym: "Rb", row: 5, col: 1, group: "group1" },
  { num: 38, sym: "Sr", row: 5, col: 2, group: "group2" },
  { num: 39, sym: "Y", row: 5, col: 3, group: "transition" },
  { num: 40, sym: "Zr", row: 5, col: 4, group: "transition" },
  { num: 41, sym: "Nb", row: 5, col: 5, group: "transition" },
  { num: 42, sym: "Mo", row: 5, col: 6, group: "transition" },
  { num: 43, sym: "Tc", row: 5, col: 7, group: "transition" },
  { num: 44, sym: "Ru", row: 5, col: 8, group: "transition" },
  { num: 45, sym: "Rh", row: 5, col: 9, group: "transition" },
  { num: 46, sym: "Pd", row: 5, col: 10, group: "transition" },
  { num: 47, sym: "Ag", row: 5, col: 11, group: "transition" },
  { num: 48, sym: "Cd", row: 5, col: 12, group: "transition" },
  { num: 49, sym: "In", row: 5, col: 13, group: "postTransition" },
  { num: 50, sym: "Sn", row: 5, col: 14, group: "postTransition" },
  { num: 51, sym: "Sb", row: 5, col: 15, group: "metalloid" },
  { num: 52, sym: "Te", row: 5, col: 16, group: "metalloid" },
  { num: 53, sym: "I", row: 5, col: 17, group: "group17" },
  { num: 54, sym: "Xe", row: 5, col: 18, group: "group18" },
  // Period 6
  { num: 55, sym: "Cs", row: 6, col: 1, group: "group1" },
  { num: 56, sym: "Ba", row: 6, col: 2, group: "group2" },
  // Lanthanides 57–71 → displayed separately
  { num: 72, sym: "Hf", row: 6, col: 4, group: "transition" },
  { num: 73, sym: "Ta", row: 6, col: 5, group: "transition" },
  { num: 74, sym: "W", row: 6, col: 6, group: "transition" },
  { num: 75, sym: "Re", row: 6, col: 7, group: "transition" },
  { num: 76, sym: "Os", row: 6, col: 8, group: "transition" },
  { num: 77, sym: "Ir", row: 6, col: 9, group: "transition" },
  { num: 78, sym: "Pt", row: 6, col: 10, group: "transition" },
  { num: 79, sym: "Au", row: 6, col: 11, group: "transition" },
  { num: 80, sym: "Hg", row: 6, col: 12, group: "transition" },
  { num: 81, sym: "Tl", row: 6, col: 13, group: "postTransition" },
  { num: 82, sym: "Pb", row: 6, col: 14, group: "postTransition" },
  { num: 83, sym: "Bi", row: 6, col: 15, group: "postTransition" },
  { num: 84, sym: "Po", row: 6, col: 16, group: "postTransition" },
  { num: 85, sym: "At", row: 6, col: 17, group: "group17" },
  { num: 86, sym: "Rn", row: 6, col: 18, group: "group18" },
  // Period 7
  { num: 87, sym: "Fr", row: 7, col: 1, group: "group1" },
  { num: 88, sym: "Ra", row: 7, col: 2, group: "group2" },
  // Actinides 89–103 → displayed separately
  { num: 104, sym: "Rf", row: 7, col: 4, group: "transition" },
  { num: 105, sym: "Db", row: 7, col: 5, group: "transition" },
  { num: 106, sym: "Sg", row: 7, col: 6, group: "transition" },
  { num: 107, sym: "Bh", row: 7, col: 7, group: "transition" },
  { num: 108, sym: "Hs", row: 7, col: 8, group: "transition" },
  { num: 109, sym: "Mt", row: 7, col: 9, group: "bg-lime-200" },
  { num: 110, sym: "Ds", row: 7, col: 10, group: "bg-lime-200" },
  { num: 111, sym: "Rg", row: 7, col: 11, group: "bg-lime-200" },
  { num: 112, sym: "Cn", row: 7, col: 12, group: "bg-lime-200" },
  { num: 113, sym: "Nh", row: 7, col: 13, group: "bg-lime-200" },
  { num: 114, sym: "Fl", row: 7, col: 14, group: "bg-lime-200" },
  { num: 115, sym: "Mc", row: 7, col: 15, group: "bg-lime-200" },
  { num: 116, sym: "Lv", row: 7, col: 16, group: "bg-lime-200" },
  { num: 117, sym: "Ts", row: 7, col: 17, group: "bg-lime-200" },
  { num: 118, sym: "Og", row: 7, col: 18, group: "bg-lime-200" },
  // Lanthanides row (displayed separately)
  { num: 57, sym: "La", row: 12, col: 3, group: "lanthanide" },
  { num: 58, sym: "Ce", row: 12, col: 4, group: "lanthanide" },
  { num: 59, sym: "Pr", row: 12, col: 5, group: "lanthanide" },
  { num: 60, sym: "Nd", row: 12, col: 6, group: "lanthanide" },
  { num: 61, sym: "Pm", row: 12, col: 7, group: "lanthanide" },
  { num: 62, sym: "Sm", row: 12, col: 8, group: "lanthanide" },
  { num: 63, sym: "Eu", row: 12, col: 9, group: "lanthanide" },
  { num: 64, sym: "Gd", row: 12, col: 10, group: "lanthanide" },
  { num: 65, sym: "Tb", row: 12, col: 11, group: "lanthanide" },
  { num: 66, sym: "Dy", row: 12, col: 12, group: "lanthanide" },
  { num: 67, sym: "Ho", row: 12, col: 13, group: "lanthanide" },
  { num: 68, sym: "Er", row: 12, col: 14, group: "lanthanide" },
  { num: 69, sym: "Tm", row: 12, col: 15, group: "lanthanide" },
  { num: 70, sym: "Yb", row: 12, col: 16, group: "lanthanide" },
  { num: 71, sym: "Lu", row: 12, col: 17, group: "lanthanide" },
  // Actinides row (displayed separately)
  { num: 89, sym: "Ac", row: 13, col: 3, group: "actinide" },
  { num: 90, sym: "Th", row: 13, col: 4, group: "actinide" },
  { num: 91, sym: "Pa", row: 13, col: 5, group: "actinide" },
  { num: 92, sym: "U", row: 13, col: 6, group: "actinide" },
  { num: 93, sym: "Np", row: 13, col: 7, group: "actinide" },
  { num: 94, sym: "Pu", row: 13, col: 8, group: "actinide" },
  { num: 95, sym: "Am", row: 13, col: 9, group: "actinide" },
  { num: 96, sym: "Cm", row: 13, col: 10, group: "actinide" },
  { num: 97, sym: "Bk", row: 13, col: 11, group: "actinide" },
  { num: 98, sym: "Cf", row: 13, col: 12, group: "actinide" },
  { num: 99, sym: "Es", row: 13, col: 13, group: "actinide" },
  { num: 100, sym: "Fm", row: 13, col: 14, group: "actinide" },
  { num: 101, sym: "Md", row: 13, col: 15, group: "actinide" },
  { num: 102, sym: "No", row: 13, col: 16, group: "actinide" },
  { num: 103, sym: "Lr", row: 13, col: 17, group: "actinide" },
];
